"""
List of Place Types and Place qualifiers
From: https://en.wiktionary.org/wiki/Template:place
Current version:
    2020-09-27T14:47:01
    https://en.wiktionary.org/w/index.php?title=Template:place&oldid=53747022
List generated by https://github.com/BoboTiG/ebook-reader-dict/wiki/%5BEN%5D-Parsing-the-'place'-template-documentation
"""

placetypes = {
    "*": {
        "article": "a",
        "display": "*",
        "preposition": "in",
    },
    "Crown dependency": {
        "article": "a",
        "display": "Crown dependency",
        "preposition": "of",
    },
    "cdep": {
        "article": "a",
        "display": "Crown dependency",
        "preposition": "of",
    },
    "First Nations reserve": {
        "article": "a",
        "display": "First Nations reserve",
        "preposition": "in",
    },
    "Indian reservation": {
        "article": "a",
        "display": "Indian reservation",
        "preposition": "in",
    },
    "ires": {
        "article": "a",
        "display": "Indian reservation",
        "preposition": "in",
    },
    "Indian reserve": {
        "article": "a",
        "display": "Indian reserve",
        "preposition": "in",
    },
    "Israeli settlement": {
        "article": "a",
        "display": "Israeli settlement",
        "preposition": "in",
    },
    "London borough": {
        "article": "a",
        "display": "London borough",
        "preposition": "of",
    },
    "lbor": {
        "article": "a",
        "display": "London borough",
        "preposition": "of",
    },
    "administrative atoll": {
        "article": "an",
        "display": "administrative atoll",
        "preposition": "of",
    },
    "administrative capital": {
        "article": "the",
        "display": "administrative capital",
        "preposition": "of",
    },
    "administrative center": {
        "article": "the",
        "display": "administrative center",
        "preposition": "of",
    },
    "administrative centre": {
        "article": "the",
        "display": "administrative centre",
        "preposition": "of",
    },
    "administrative county": {
        "article": "an",
        "display": "administrative county",
        "preposition": "in",
    },
    "administrative district": {
        "article": "an",
        "display": "administrative district",
        "preposition": "in",
    },
    "administrative headquarters": {
        "article": "the",
        "display": "administrative headquarters",
        "preposition": "of",
    },
    "administrative region": {
        "article": "an",
        "display": "administrative region",
        "preposition": "in",
    },
    "adr": {
        "article": "an",
        "display": "administrative region",
        "preposition": "in",
    },
    "administrative seat": {
        "article": "the",
        "display": "administrative seat",
        "preposition": "of",
    },
    "administrative village": {
        "article": "an",
        "display": "administrative village",
        "preposition": "of",
    },
    "airport": {
        "article": "an",
        "display": "airport",
        "preposition": "in",
    },
    "ancient capital": {
        "article": "the",
        "display": "ancient capital",
        "preposition": "of",
    },
    "ancient city": {
        "article": "an",
        "display": "ancient city",
        "preposition": "in",
    },
    "ancient hamlet": {
        "article": "an",
        "display": "ancient hamlet",
        "preposition": "in",
    },
    "ancient settlement": {
        "article": "an",
        "display": "ancient settlement",
        "preposition": "in",
    },
    "ancient town": {
        "article": "an",
        "display": "ancient town",
        "preposition": "in",
    },
    "ancient village": {
        "article": "an",
        "display": "ancient village",
        "preposition": "in",
    },
    "archipelago": {
        "article": "an",
        "display": "archipelago",
        "preposition": "in",
    },
    "arch": {
        "article": "an",
        "display": "archipelago",
        "preposition": "in",
    },
    "area": {
        "article": "an",
        "display": "area",
        "preposition": "in",
    },
    "arrondissement": {
        "article": "an",
        "display": "arrondissement",
        "preposition": "of",
    },
    "associated province": {
        "article": "an",
        "display": "associated province",
        "preposition": "of",
    },
    "atoll": {
        "article": "an",
        "display": "atoll",
        "preposition": "in",
    },
    "autonomous community": {
        "article": "an",
        "display": "autonomous community",
        "preposition": "of",
    },
    "acomm": {
        "article": "an",
        "display": "autonomous community",
        "preposition": "of",
    },
    "autonomous island": {
        "article": "an",
        "display": "autonomous island",
        "preposition": "of",
    },
    "autonomous oblast": {
        "article": "an",
        "display": "autonomous oblast",
        "preposition": "of",
    },
    "aobl": {
        "article": "an",
        "display": "autonomous oblast",
        "preposition": "of",
    },
    "autonomous okrug": {
        "article": "an",
        "display": "autonomous okrug",
        "preposition": "of",
    },
    "aokr": {
        "article": "an",
        "display": "autonomous okrug",
        "preposition": "of",
    },
    "autonomous prefecture": {
        "article": "an",
        "display": "autonomous prefecture",
        "preposition": "in",
    },
    "apref": {
        "article": "an",
        "display": "autonomous prefecture",
        "preposition": "in",
    },
    "autonomous province": {
        "article": "an",
        "display": "autonomous province",
        "preposition": "in",
    },
    "ap": {
        "article": "an",
        "display": "autonomous province",
        "preposition": "in",
    },
    "autonomous region": {
        "article": "an",
        "display": "autonomous region",
        "preposition": "of",
    },
    "ar": {
        "article": "an",
        "display": "autonomous region",
        "preposition": "of",
    },
    "autonomous republic": {
        "article": "an",
        "display": "autonomous republic",
        "preposition": "of",
    },
    "arep": {
        "article": "an",
        "display": "autonomous republic",
        "preposition": "of",
    },
    "autonomous territory": {
        "article": "an",
        "display": "autonomous territory",
        "preposition": "of",
    },
    "aterr": {
        "article": "an",
        "display": "autonomous territory",
        "preposition": "of",
    },
    "bailiwick": {
        "article": "a",
        "display": "bailiwick",
        "preposition": "in",
    },
    "barangay": {
        "article": "a",
        "display": "barangay",
        "preposition": "of",
    },
    "barrio": {
        "article": "a",
        "display": "barrio",
        "preposition": "of",
    },
    "bay": {
        "article": "a",
        "display": "bay",
        "preposition": "of",
    },
    "beach": {
        "article": "a",
        "display": "beach",
        "preposition": "in",
    },
    "beach resort": {
        "article": "a",
        "display": "beach resort",
        "preposition": "in",
    },
    "bishopric": {
        "article": "a",
        "display": "bishopric",
        "preposition": "in",
    },
    "borough": {
        "article": "a",
        "display": "borough",
        "preposition": "of",
    },
    "bor": {
        "article": "a",
        "display": "borough",
        "preposition": "of",
    },
    "borough seat": {
        "article": "the",
        "display": "borough seat",
        "preposition": "of",
    },
    "built-up area": {
        "article": "a",
        "display": "built-up area",
        "preposition": "in",
    },
    "burgh": {
        "article": "a",
        "display": "burgh",
        "preposition": "of",
    },
    "canton": {
        "article": "a",
        "display": "canton",
        "preposition": "of",
    },
    "can": {
        "article": "a",
        "display": "canton",
        "preposition": "of",
    },
    "cape": {
        "article": "a",
        "display": "cape",
        "preposition": "in",
    },
    "capital": {
        "article": "the",
        "display": "capital",
        "preposition": "of",
    },
    "capital city": {
        "article": "the",
        "display": "capital city",
        "preposition": "of",
    },
    "caplc": {
        "article": "the",
        "display": "capital and largest city",
        "preposition": "of",
    },
    "caravan city": {
        "article": "a",
        "display": "caravan city",
        "preposition": "in",
    },
    "cathedral city": {
        "article": "a",
        "display": "cathedral city",
        "preposition": "in",
    },
    "cattle station": {
        "article": "a",
        "display": "cattle station",
        "preposition": "in",
    },
    "census area": {
        "article": "a",
        "display": "census area",
        "preposition": "in",
    },
    "census division": {
        "article": "a",
        "display": "census division",
        "preposition": "of",
    },
    "census-designated place": {
        "article": "a",
        "display": "census-designated place",
        "preposition": "in",
    },
    "CDP": {
        "article": "a",
        "display": "census-designated place",
        "preposition": "in",
    },
    " cdp": {
        "article": "a",
        "display": "census-designated place",
        "preposition": "in",
    },
    "central business district": {
        "article": "a",
        "display": "central business district",
        "preposition": "of",
    },
    "cercle": {
        "article": "a",
        "display": "cercle",
        "preposition": "of",
    },
    "ceremonial county": {
        "article": "a",
        "display": "ceremonial county",
        "preposition": "of",
    },
    "chain of islands": {
        "article": "a",
        "display": "chain of islands",
        "preposition": "in",
    },
    "channel": {
        "article": "a",
        "display": "channel",
        "preposition": "in",
    },
    "charter community": {
        "article": "a",
        "display": "charter community",
        "preposition": "in",
    },
    "city": {
        "article": "a",
        "display": "city",
        "preposition": "in",
    },
    "city-state": {
        "article": "a",
        "display": "city-state",
        "preposition": "in",
    },
    "civil parish": {
        "article": "a",
        "display": "civil parish",
        "preposition": "of",
    },
    "cpar": {
        "article": "a",
        "display": "civil parish",
        "preposition": "of",
    },
    "coal town": {
        "article": "a",
        "display": "coal town",
        "preposition": "in",
    },
    "collectivity": {
        "article": "a",
        "display": "collectivity",
        "preposition": "of",
    },
    "coll": {
        "article": "a",
        "display": "collectivity",
        "preposition": "of",
    },
    "colony": {
        "article": "a",
        "display": "colony",
        "preposition": "of",
    },
    "commandery": {
        "article": "a",
        "display": "commandery",
        "preposition": "of",
    },
    "commonwealth": {
        "article": "a",
        "display": "commonwealth",
        "preposition": "of",
    },
    "commune": {
        "article": "a",
        "display": "commune",
        "preposition": "of",
    },
    "community": {
        "article": "a",
        "display": "community",
        "preposition": "in",
    },
    "comm": {
        "article": "a",
        "display": "community",
        "preposition": "in",
    },
    "community development block": {
        "article": "a",
        "display": "community development block",
        "preposition": "in",
    },
    "cdblock": {
        "article": "a",
        "display": "community development block",
        "preposition": "in",
    },
    "constituency": {
        "article": "a",
        "display": "constituency",
        "preposition": "of",
    },
    "constituent country": {
        "article": "a",
        "display": "constituent country",
        "preposition": "in",
    },
    "cc": {
        "article": "a",
        "display": "constituent country",
        "preposition": "in",
    },
    "continent": {
        "article": "a",
        "display": "continent",
        "preposition": "in",
    },
    "cont": {
        "article": "a",
        "display": "continent",
        "preposition": "in",
    },
    "contregion": {
        "article": "a",
        "display": "continental region",
        "preposition": "of",
    },
    "council area": {
        "article": "a",
        "display": "council area",
        "preposition": "of",
    },
    "carea": {
        "article": "a",
        "display": "council area",
        "preposition": "of",
    },
    "country": {
        "article": "a",
        "display": "country",
        "preposition": "in",
    },
    "c": {
        "article": "a",
        "display": "country",
        "preposition": "in",
    },
    "county": {
        "article": "a",
        "display": "county",
        "preposition": "of",
    },
    "co": {
        "article": "a",
        "display": "county",
        "preposition": "of",
    },
    "county borough": {
        "article": "a",
        "display": "county borough",
        "preposition": "of",
    },
    "cobor": {
        "article": "a",
        "display": "county borough",
        "preposition": "of",
    },
    "county seat": {
        "article": "the",
        "display": "county seat",
        "preposition": "of",
    },
    "county town": {
        "article": "the",
        "display": "county town",
        "preposition": "of",
    },
    "county-administered city": {
        "article": "a",
        "display": "county-administered city",
        "preposition": "in",
    },
    "county-controlled city": {
        "article": "a",
        "display": "county-controlled city",
        "preposition": "in",
    },
    "county-level city": {
        "article": "a",
        "display": "county-level city",
        "preposition": "in",
    },
    "colcity": {
        "article": "a",
        "display": "county-level city",
        "preposition": "in",
    },
    "crown dependency": {
        "article": "a",
        "display": "crown dependency",
        "preposition": "of",
    },
    "delegation": {
        "article": "a",
        "display": "delegation",
        "preposition": "of",
    },
    "department": {
        "article": "a",
        "display": "department",
        "preposition": "of",
    },
    "dept": {
        "article": "a",
        "display": "department",
        "preposition": "of",
    },
    "department capital": {
        "article": "the",
        "display": "department capital",
        "preposition": "of",
    },
    "departmental capital": {
        "article": "the",
        "display": "department capital",
        "preposition": "of",
    },
    "dependency": {
        "article": "a",
        "display": "dependency",
        "preposition": "of",
    },
    "dep": {
        "article": "a",
        "display": "dependency",
        "preposition": "of",
    },
    "dependent territory": {
        "article": "a",
        "display": "dependent territory",
        "preposition": "of",
    },
    "desert": {
        "article": "a",
        "display": "desert",
        "preposition": "in",
    },
    "deserted mediaeval village": {
        "article": "a",
        "display": "deserted mediaeval village",
        "preposition": "in",
    },
    "deserted medieval village": {
        "article": "a",
        "display": "deserted medieval village",
        "preposition": "in",
    },
    "direct-administered municipality": {
        "article": "a",
        "display": "direct-administered municipality",
        "preposition": "of",
    },
    "direct-controlled municipality": {
        "article": "a",
        "display": "direct-controlled municipality",
        "preposition": "of",
    },
    "distributary": {
        "article": "a",
        "display": "distributary",
        "preposition": "in",
    },
    "district": {
        "article": "a",
        "display": "district",
        "preposition": "of",
    },
    "dist": {
        "article": "a",
        "display": "district",
        "preposition": "of",
    },
    "district capital": {
        "article": "the",
        "display": "district capital",
        "preposition": "of",
    },
    "district headquarters": {
        "article": "the",
        "display": "district headquarters",
        "preposition": "of",
    },
    "district municipality": {
        "article": "a",
        "display": "district municipality",
        "preposition": "of",
    },
    "distmun": {
        "article": "a",
        "display": "district municipality",
        "preposition": "of",
    },
    "districts and autonomous region": {
        "article": "a",
        "display": "districts and autonomous region",
        "preposition": "of",
    },
    "division": {
        "article": "a",
        "display": "division",
        "preposition": "of",
    },
    "div": {
        "article": "a",
        "display": "division",
        "preposition": "of",
    },
    "dormant volcano": {
        "article": "a",
        "display": "dormant volcano",
        "preposition": "in",
    },
    "duchy": {
        "article": "a",
        "display": "duchy",
        "preposition": "in",
    },
    "emirate": {
        "article": "an",
        "display": "emirate",
        "preposition": "of",
    },
    "empire": {
        "article": "an",
        "display": "empire",
        "preposition": "in",
    },
    "enclave": {
        "article": "an",
        "display": "enclave",
        "preposition": "of",
    },
    "entity": {
        "article": "an",
        "display": "entity",
        "preposition": "of",
    },
    "ethnographic region": {
        "article": "an",
        "display": "ethnographic region",
        "preposition": "of",
    },
    "exclave": {
        "article": "an",
        "display": "exclave",
        "preposition": "of",
    },
    "external territory": {
        "article": "an",
        "display": "external territory",
        "preposition": "of",
    },
    "federal city": {
        "article": "a",
        "display": "federal city",
        "preposition": "of",
    },
    "federal subject": {
        "article": "a",
        "display": "federal subject",
        "preposition": "of",
    },
    "federal territory": {
        "article": "a",
        "display": "federal territory",
        "preposition": "of",
    },
    "fictional location": {
        "article": "a",
        "display": "fictional location",
        "preposition": "in",
    },
    "fjord": {
        "article": "a",
        "display": "fjord",
        "preposition": "in",
    },
    "forest": {
        "article": "a",
        "display": "forest",
        "preposition": "in",
    },
    "former autonomous territory": {
        "article": "a",
        "display": "former autonomous territory",
        "preposition": "in",
    },
    "former colony": {
        "article": "a",
        "display": "former colony",
        "preposition": "in",
    },
    "former maritime republic": {
        "article": "a",
        "display": "former maritime republic",
        "preposition": "in",
    },
    "former polity": {
        "article": "a",
        "display": "former polity",
        "preposition": "in",
    },
    "former separatist state": {
        "article": "a",
        "display": "former separatist state",
        "preposition": "in",
    },
    "geographical region": {
        "article": "a",
        "display": "geographical region",
        "preposition": "of",
    },
    "gewog": {
        "article": "a",
        "display": "gewog",
        "preposition": "of",
    },
    "ghost town": {
        "article": "a",
        "display": "ghost town",
        "preposition": "in",
    },
    "glen": {
        "article": "a",
        "display": "glen",
        "preposition": "in",
    },
    "governorate": {
        "article": "a",
        "display": "governorate",
        "preposition": "of",
    },
    "gov": {
        "article": "a",
        "display": "governorate",
        "preposition": "of",
    },
    " govnat": {
        "article": "a",
        "display": "governorate",
        "preposition": "of",
    },
    "group of islands": {
        "article": "a",
        "display": "group of islands",
        "preposition": "in",
    },
    "gulf": {
        "article": "a",
        "display": "gulf",
        "preposition": "of",
    },
    "hamlet": {
        "article": "a",
        "display": "hamlet",
        "preposition": "in",
    },
    "harbor city": {
        "article": "a",
        "display": "harbor city",
        "preposition": "in",
    },
    "harbor town": {
        "article": "a",
        "display": "harbor town",
        "preposition": "in",
    },
    "harbour city": {
        "article": "a",
        "display": "harbour city",
        "preposition": "in",
    },
    "harbour town": {
        "article": "a",
        "display": "harbour town",
        "preposition": "in",
    },
    "headland": {
        "article": "a",
        "display": "headland",
        "preposition": "in",
    },
    "headquarters": {
        "article": "the",
        "display": "headquarters",
        "preposition": "of",
    },
    "heath": {
        "article": "a",
        "display": "heath",
        "preposition": "in",
    },
    "hill": {
        "article": "a",
        "display": "hill",
        "preposition": "in",
    },
    "hill station": {
        "article": "a",
        "display": "hill station",
        "preposition": "in",
    },
    "hill town": {
        "article": "a",
        "display": "hill town",
        "preposition": "in",
    },
    "historical autonomous republic": {
        "article": "a",
        "display": "historical autonomous republic",
        "preposition": "of",
    },
    "historical autonomous territory": {
        "article": "a",
        "display": "historical autonomous territory",
        "preposition": "of",
    },
    "historical bailiwick": {
        "article": "a",
        "display": "historical bailiwick",
        "preposition": "in",
    },
    "historical barangay": {
        "article": "a",
        "display": "historical barangay",
        "preposition": "of",
    },
    "historical bishopric": {
        "article": "a",
        "display": "historical bishopric",
        "preposition": "in",
    },
    "historical borough": {
        "article": "a",
        "display": "historical borough",
        "preposition": "of",
    },
    "historical canton": {
        "article": "a",
        "display": "historical canton",
        "preposition": "of",
    },
    "historical capital": {
        "article": "the",
        "display": "historical capital",
        "preposition": "of",
    },
    "historical city": {
        "article": "a",
        "display": "historical city",
        "preposition": "in",
    },
    "historical civil parish": {
        "article": "a",
        "display": "historical civil parish",
        "preposition": "of",
    },
    "historical civilisation": {
        "article": "a",
        "display": "historical civilisation",
        "preposition": "in",
    },
    "historical civilization": {
        "article": "a",
        "display": "historical civilization",
        "preposition": "in",
    },
    "historical colony": {
        "article": "a",
        "display": "historical colony",
        "preposition": "in",
    },
    "historical commandery": {
        "article": "a",
        "display": "historical commandery",
        "preposition": "of",
    },
    "historical commonwealth": {
        "article": "a",
        "display": "historical commonwealth",
        "preposition": "in",
    },
    "historical commune": {
        "article": "a",
        "display": "historical commune",
        "preposition": "of",
    },
    "historical council area": {
        "article": "a",
        "display": "historical council area",
        "preposition": "of",
    },
    "historical country": {
        "article": "a",
        "display": "historical country",
        "preposition": "in",
    },
    "historical county": {
        "article": "a",
        "display": "historical county",
        "preposition": "of",
    },
    "historical county borough": {
        "article": "a",
        "display": "historical county borough",
        "preposition": "of",
    },
    "historical crown dependency": {
        "article": "a",
        "display": "historical crown dependency",
        "preposition": "in",
    },
    "historical department": {
        "article": "a",
        "display": "historical department",
        "preposition": "of",
    },
    "historical dependency": {
        "article": "a",
        "display": "historical dependency",
        "preposition": "in",
    },
    "historical district": {
        "article": "a",
        "display": "historical district",
        "preposition": "of",
    },
    "historical division": {
        "article": "a",
        "display": "historical division",
        "preposition": "of",
    },
    "historical duchy": {
        "article": "a",
        "display": "historical duchy",
        "preposition": "in",
    },
    "historical empire": {
        "article": "a",
        "display": "historical empire",
        "preposition": "in",
    },
    "historical governorate": {
        "article": "a",
        "display": "historical governorate",
        "preposition": "of",
    },
    "historical hamlet": {
        "article": "a",
        "display": "historical hamlet",
        "preposition": "in",
    },
    "historical kingdom": {
        "article": "a",
        "display": "historical kingdom",
        "preposition": "in",
    },
    "historical krai": {
        "article": "a",
        "display": "historical krai",
        "preposition": "of",
    },
    "historical maritime republic": {
        "article": "a",
        "display": "historical maritime republic",
        "preposition": "in",
    },
    "historical metropolitan borough": {
        "article": "a",
        "display": "historical metropolitan borough",
        "preposition": "of",
    },
    "historical municipality": {
        "article": "a",
        "display": "historical municipality",
        "preposition": "of",
    },
    "historical oblast": {
        "article": "a",
        "display": "historical oblast",
        "preposition": "of",
    },
    "historical okrug": {
        "article": "a",
        "display": "historical okrug",
        "preposition": "of",
    },
    "historical parish": {
        "article": "a",
        "display": "historical parish",
        "preposition": "of",
    },
    "historical periphery": {
        "article": "a",
        "display": "historical periphery",
        "preposition": "of",
    },
    "historical political subdivision": {
        "article": "a",
        "display": "historical political subdivision",
        "preposition": "of",
    },
    "historical polity": {
        "article": "a",
        "display": "historical polity",
        "preposition": "in",
    },
    "historical prefecture": {
        "article": "a",
        "display": "historical prefecture",
        "preposition": "of",
    },
    "historical province": {
        "article": "a",
        "display": "historical province",
        "preposition": "of",
    },
    "historical regency": {
        "article": "a",
        "display": "historical regency",
        "preposition": "of",
    },
    "historical region": {
        "article": "a",
        "display": "historical region",
        "preposition": "in",
    },
    "historical regional unit": {
        "article": "a",
        "display": "historical regional unit",
        "preposition": "of",
    },
    "historical republic": {
        "article": "a",
        "display": "historical republic",
        "preposition": "in",
    },
    "historical satrapy": {
        "article": "a",
        "display": "historical satrapy",
        "preposition": "in",
    },
    "historical separatist state": {
        "article": "a",
        "display": "historical separatist state",
        "preposition": "in",
    },
    "historical settlement": {
        "article": "a",
        "display": "historical settlement",
        "preposition": "in",
    },
    "historical state": {
        "article": "a",
        "display": "historical state",
        "preposition": "in",
    },
    "historical subdistrict": {
        "article": "a",
        "display": "historical subdistrict",
        "preposition": "of",
    },
    "historical subdivision": {
        "article": "a",
        "display": "historical subdivision",
        "preposition": "of",
    },
    "historical subprefecture": {
        "article": "a",
        "display": "historical subprefecture",
        "preposition": "of",
    },
    "historical town": {
        "article": "a",
        "display": "historical town",
        "preposition": "in",
    },
    "historical village": {
        "article": "a",
        "display": "historical village",
        "preposition": "in",
    },
    "historical voivodeship": {
        "article": "a",
        "display": "historical voivodeship",
        "preposition": "of",
    },
    "home rule city": {
        "article": "a",
        "display": "home rule city",
        "preposition": "in",
    },
    "home-rule city": {
        "article": "a",
        "display": "home rule city",
        "preposition": "in",
    },
    "home rule municipality": {
        "article": "a",
        "display": "home rule municipality",
        "preposition": "of",
    },
    "home-rule municipality": {
        "article": "a",
        "display": "home rule municipality",
        "preposition": "of",
    },
    "housing estate": {
        "article": "a",
        "display": "housing estate",
        "preposition": "in",
    },
    "inactive volcano": {
        "article": "an",
        "display": "inactive volcano",
        "preposition": "in",
    },
    "independent city": {
        "article": "an",
        "display": "independent city",
        "preposition": "in",
    },
    "independent town": {
        "article": "an",
        "display": "independent town",
        "preposition": "in",
    },
    "inner city area": {
        "article": "an",
        "display": "inner city area",
        "preposition": "of",
    },
    "inner-city area": {
        "article": "an",
        "display": "inner city area",
        "preposition": "of",
    },
    "island": {
        "article": "an",
        "display": "island",
        "preposition": "in",
    },
    "isl": {
        "article": "an",
        "display": "island",
        "preposition": "in",
    },
    "island country": {
        "article": "an",
        "display": "island country",
        "preposition": "in",
    },
    "island municipality": {
        "article": "an",
        "display": "island municipality",
        "preposition": "of",
    },
    "judicial capital": {
        "article": "the",
        "display": "judicial capital",
        "preposition": "of",
    },
    "kibbutz": {
        "article": "a",
        "display": "kibbutz",
        "preposition": "in",
    },
    "kingdom": {
        "article": "a",
        "display": "kingdom",
        "preposition": "in",
    },
    "krai": {
        "article": "a",
        "display": "krai",
        "preposition": "of",
    },
    "lake": {
        "article": "a",
        "display": "lake",
        "preposition": "in",
    },
    "largest city": {
        "article": "the",
        "display": "largest city",
        "preposition": "in",
    },
    "legislative capital": {
        "article": "the",
        "display": "legislative capital",
        "preposition": "of",
    },
    "lieutenancy area": {
        "article": "a",
        "display": "lieutenancy area",
        "preposition": "in",
    },
    "local authority district": {
        "article": "a",
        "display": "local authority district",
        "preposition": "of",
    },
    "local council": {
        "article": "a",
        "display": "local council",
        "preposition": "of",
    },
    "local government area": {
        "article": "a",
        "display": "local government area",
        "preposition": "of",
    },
    "lgarea": {
        "article": "a",
        "display": "local government area",
        "preposition": "of",
    },
    "local government district": {
        "article": "a",
        "display": "local government district",
        "preposition": "of",
    },
    "lgdist": {
        "article": "a",
        "display": "local government district",
        "preposition": "of",
    },
    "local government district with borough status": {
        "article": "a",
        "display": "local government district with borough status",
        "preposition": "of",
    },
    "local urban district": {
        "article": "a",
        "display": "local urban district",
        "preposition": "in",
    },
    "locality": {
        "article": "a",
        "display": "locality",
        "preposition": "in",
    },
    "macroregion": {
        "article": "a",
        "display": "macroregion",
        "preposition": "of",
    },
    "marginal sea": {
        "article": "a",
        "display": "marginal sea",
        "preposition": "of",
    },
    "market city": {
        "article": "a",
        "display": "market city",
        "preposition": "in",
    },
    "market town": {
        "article": "a",
        "display": "market town",
        "preposition": "in",
    },
    "mediaeval capital": {
        "article": "the",
        "display": "mediaeval capital",
        "preposition": "of",
    },
    "mediaeval city": {
        "article": "a",
        "display": "mediaeval city",
        "preposition": "in",
    },
    "mediaeval hamlet": {
        "article": "a",
        "display": "mediaeval hamlet",
        "preposition": "in",
    },
    "mediaeval town": {
        "article": "a",
        "display": "mediaeval town",
        "preposition": "in",
    },
    "mediaeval village": {
        "article": "a",
        "display": "mediaeval village",
        "preposition": "in",
    },
    "medieval capital": {
        "article": "the",
        "display": "medieval capital",
        "preposition": "of",
    },
    "medieval city": {
        "article": "a",
        "display": "medieval city",
        "preposition": "in",
    },
    "medieval hamlet": {
        "article": "a",
        "display": "medieval hamlet",
        "preposition": "in",
    },
    "medieval town": {
        "article": "a",
        "display": "medieval town",
        "preposition": "in",
    },
    "medieval village": {
        "article": "a",
        "display": "medieval village",
        "preposition": "in",
    },
    "megacity": {
        "article": "a",
        "display": "megacity",
        "preposition": "in",
    },
    "metro station": {
        "article": "a",
        "display": "metro station",
        "preposition": "in",
    },
    "metropolitan borough": {
        "article": "a",
        "display": "metropolitan borough",
        "preposition": "of",
    },
    "metbor": {
        "article": "a",
        "display": "metropolitan borough",
        "preposition": "of",
    },
    "metropolitan city": {
        "article": "a",
        "display": "metropolitan city",
        "preposition": "of",
    },
    "metcity": {
        "article": "a",
        "display": "metropolitan city",
        "preposition": "of",
    },
    "metropolitan county": {
        "article": "a",
        "display": "metropolitan county",
        "preposition": "of",
    },
    "microdistrict": {
        "article": "a",
        "display": "microdistrict",
        "preposition": "of",
    },
    "microstate": {
        "article": "a",
        "display": "microstate",
        "preposition": "in",
    },
    "minster town": {
        "article": "a",
        "display": "minster town",
        "preposition": "in",
    },
    "moor": {
        "article": "a",
        "display": "moor",
        "preposition": "in",
    },
    "moorland": {
        "article": "a",
        "display": "moorland",
        "preposition": "in",
    },
    "mountain": {
        "article": "a",
        "display": "mountain",
        "preposition": "in",
    },
    "mtn": {
        "article": "a",
        "display": "mountain",
        "preposition": "in",
    },
    "mountain indigenous district": {
        "article": "a",
        "display": "mountain indigenous district",
        "preposition": "of",
    },
    "mountain indigenous township": {
        "article": "a",
        "display": "mountain indigenous township",
        "preposition": "in",
    },
    "mountain pass": {
        "article": "a",
        "display": "mountain pass",
        "preposition": "in",
    },
    "mountain range": {
        "article": "a",
        "display": "mountain range",
        "preposition": "in",
    },
    "range": {
        "article": "a",
        "display": "mountain range",
        "preposition": "in",
    },
    "mountainous region": {
        "article": "a",
        "display": "mountainous region",
        "preposition": "of",
    },
    "mukim": {
        "article": "a",
        "display": "mukim",
        "preposition": "of",
    },
    "municipal district": {
        "article": "a",
        "display": "municipal district",
        "preposition": "of",
    },
    "mundist": {
        "article": "a",
        "display": "municipal district",
        "preposition": "of",
    },
    "municipality": {
        "article": "a",
        "display": "municipality",
        "preposition": "of",
    },
    "mun": {
        "article": "a",
        "display": "municipality",
        "preposition": "of",
    },
    "municipality with city status": {
        "article": "a",
        "display": "municipality with city status",
        "preposition": "of",
    },
    "mythological location": {
        "article": "a",
        "display": "mythological location",
        "preposition": "in",
    },
    "national capital": {
        "article": "the",
        "display": "national capital",
        "preposition": "of",
    },
    "national park": {
        "article": "a",
        "display": "national park",
        "preposition": "in",
    },
    "neighborhood": {
        "article": "a",
        "display": "neighborhood",
        "preposition": "of",
    },
    "neighbourhood": {
        "article": "a",
        "display": "neighbourhood",
        "preposition": "of",
    },
    "new town": {
        "article": "a",
        "display": "new town",
        "preposition": "in",
    },
    "non-city capital": {
        "article": "the",
        "display": "capital",
        "preposition": "of",
    },
    "non-metropolitan county": {
        "article": "a",
        "display": "non-metropolitan county",
        "preposition": "of",
    },
    "nonmetropolitan county": {
        "article": "a",
        "display": "non-metropolitan county",
        "preposition": "of",
    },
    "non-metropolitan district": {
        "article": "a",
        "display": "non-metropolitan district",
        "preposition": "of",
    },
    "oblast": {
        "article": "an",
        "display": "oblast",
        "preposition": "of",
    },
    "obl": {
        "article": "an",
        "display": "oblast",
        "preposition": "of",
    },
    "ocean": {
        "article": "an",
        "display": "ocean",
        "preposition": "in",
    },
    "okrug": {
        "article": "an",
        "display": "okrug",
        "preposition": "of",
    },
    "okr": {
        "article": "an",
        "display": "okrug",
        "preposition": "of",
    },
    "overseas collectivity": {
        "article": "an",
        "display": "overseas collectivity",
        "preposition": "of",
    },
    "overseas department": {
        "article": "an",
        "display": "overseas department",
        "preposition": "of",
    },
    "overseas territory": {
        "article": "an",
        "display": "overseas territory",
        "preposition": "of",
    },
    "parish": {
        "article": "a",
        "display": "parish",
        "preposition": "of",
    },
    "par": {
        "article": "a",
        "display": "parish",
        "preposition": "of",
    },
    "parish municipality": {
        "article": "a",
        "display": "parish municipality",
        "preposition": "of",
    },
    "parmun": {
        "article": "a",
        "display": "parish municipality",
        "preposition": "of",
    },
    "parish seat": {
        "article": "the",
        "display": "parish seat",
        "preposition": "of",
    },
    "park": {
        "article": "a",
        "display": "park",
        "preposition": "in",
    },
    "pass": {
        "article": "a",
        "display": "pass",
        "preposition": "in",
    },
    "peninsula": {
        "article": "a",
        "display": "peninsula",
        "preposition": "in",
    },
    "pen": {
        "article": "a",
        "display": "peninsula",
        "preposition": "in",
    },
    "periphery": {
        "article": "a",
        "display": "periphery",
        "preposition": "of",
    },
    "planned community": {
        "article": "a",
        "display": "planned community",
        "preposition": "in",
    },
    "polity": {
        "article": "a",
        "display": "polity",
        "preposition": "in",
    },
    "populated place": {
        "article": "a",
        "display": "locality",
        "preposition": "in",
    },
    "port": {
        "article": "a",
        "display": "port",
        "preposition": "in",
    },
    "port city": {
        "article": "a",
        "display": "port city",
        "preposition": "in",
    },
    "port town": {
        "article": "a",
        "display": "port town",
        "preposition": "in",
    },
    "prefecture": {
        "article": "a",
        "display": "prefecture",
        "preposition": "of",
    },
    "pref": {
        "article": "a",
        "display": "prefecture",
        "preposition": "of",
    },
    "prefecture-level city": {
        "article": "a",
        "display": "prefecture-level city",
        "preposition": "in",
    },
    "preflcity": {
        "article": "a",
        "display": "prefecture-level city",
        "preposition": "in",
    },
    "province": {
        "article": "a",
        "display": "province",
        "preposition": "of",
    },
    "p": {
        "article": "a",
        "display": "province",
        "preposition": "of",
    },
    "provincial capital": {
        "article": "the",
        "display": "provincial capital",
        "preposition": "of",
    },
    "quarter": {
        "article": "a",
        "display": "quarter",
        "preposition": "of",
    },
    "raion": {
        "article": "a",
        "display": "raion",
        "preposition": "of",
    },
    "regency": {
        "article": "a",
        "display": "regency",
        "preposition": "of",
    },
    "region": {
        "article": "a",
        "display": "region",
        "preposition": "of",
    },
    "r": {
        "article": "a",
        "display": "region",
        "preposition": "of",
    },
    "regional capital": {
        "article": "the",
        "display": "regional capital",
        "preposition": "of",
    },
    "regional county municipality": {
        "article": "a",
        "display": "regional county municipality",
        "preposition": "of",
    },
    "rcomun": {
        "article": "a",
        "display": "regional county municipality",
        "preposition": "of",
    },
    "regional district": {
        "article": "a",
        "display": "regional district",
        "preposition": "of",
    },
    "rdist": {
        "article": "a",
        "display": "regional district",
        "preposition": "of",
    },
    "regional municipality": {
        "article": "a",
        "display": "regional municipality",
        "preposition": "of",
    },
    "rmun": {
        "article": "a",
        "display": "regional municipality",
        "preposition": "of",
    },
    "regional unit": {
        "article": "a",
        "display": "regional unit",
        "preposition": "of",
    },
    "runit": {
        "article": "a",
        "display": "regional unit",
        "preposition": "of",
    },
    "registration county": {
        "article": "a",
        "display": "registration county",
        "preposition": "in",
    },
    "republic": {
        "article": "a",
        "display": "republic",
        "preposition": "of",
    },
    "rep": {
        "article": "a",
        "display": "republic",
        "preposition": "of",
    },
    "research base": {
        "article": "a",
        "display": "research base",
        "preposition": "in",
    },
    "residental area": {
        "article": "a",
        "display": "residential area",
        "preposition": "in",
    },
    "resort city": {
        "article": "a",
        "display": "resort city",
        "preposition": "in",
    },
    "resort town": {
        "article": "a",
        "display": "resort town",
        "preposition": "in",
    },
    "river": {
        "article": "a",
        "display": "river",
        "preposition": "in",
    },
    "riv": {
        "article": "a",
        "display": "river",
        "preposition": "in",
    },
    "royal borough": {
        "article": "a",
        "display": "royal borough",
        "preposition": "of",
    },
    "robor": {
        "article": "a",
        "display": "royal borough",
        "preposition": "of",
    },
    "royal burgh": {
        "article": "a",
        "display": "royal burgh",
        "preposition": "of",
    },
    "royal capital": {
        "article": "the",
        "display": "royal capital",
        "preposition": "of",
    },
    "rural community": {
        "article": "a",
        "display": "rural community",
        "preposition": "in",
    },
    "rural municipality": {
        "article": "a",
        "display": "rural municipality",
        "preposition": "of",
    },
    "rurmun": {
        "article": "a",
        "display": "rural municipality",
        "preposition": "of",
    },
    "rural township": {
        "article": "a",
        "display": "rural township",
        "preposition": "in",
    },
    "satrapy": {
        "article": "a",
        "display": "satrapy",
        "preposition": "of",
    },
    "sea": {
        "article": "a",
        "display": "sea",
        "preposition": "in",
    },
    "seaport": {
        "article": "a",
        "display": "seaport",
        "preposition": "in",
    },
    "self-administered division": {
        "article": "a",
        "display": "self-administered division",
        "preposition": "of",
    },
    "self-administered zone": {
        "article": "a",
        "display": "self-administered zone",
        "preposition": "of",
    },
    "settlement": {
        "article": "a",
        "display": "settlement",
        "preposition": "in",
    },
    "sheading": {
        "article": "a",
        "display": "sheading",
        "preposition": "of",
    },
    "sheep station": {
        "article": "a",
        "display": "sheep station",
        "preposition": "in",
    },
    "shire": {
        "article": "a",
        "display": "shire",
        "preposition": "of",
    },
    "shire county": {
        "article": "a",
        "display": "shire county",
        "preposition": "of",
    },
    "shire town": {
        "article": "the",
        "display": "shire town",
        "preposition": "of",
    },
    "ski resort town": {
        "article": "a",
        "display": "ski resort town",
        "preposition": "in",
    },
    "spa city": {
        "article": "a",
        "display": "spa city",
        "preposition": "in",
    },
    "spa town": {
        "article": "a",
        "display": "spa town",
        "preposition": "in",
    },
    "special administrative region": {
        "article": "a",
        "display": "special administrative region",
        "preposition": "of",
    },
    "sar": {
        "article": "a",
        "display": "special administrative region",
        "preposition": "of",
    },
    "special collectivity": {
        "article": "a",
        "display": "special collectivity",
        "preposition": "in",
    },
    "special ward": {
        "article": "a",
        "display": "special ward",
        "preposition": "of",
    },
    "spit": {
        "article": "a",
        "display": "spit",
        "preposition": "in",
    },
    "star": {
        "article": "a",
        "display": "star",
        "preposition": "in",
    },
    "state": {
        "article": "a",
        "display": "state",
        "preposition": "of",
    },
    "s": {
        "article": "a",
        "display": "state",
        "preposition": "of",
    },
    "state capital": {
        "article": "the",
        "display": "state capital",
        "preposition": "of",
    },
    "state park": {
        "article": "a",
        "display": "state park",
        "preposition": "in",
    },
    "statutory city": {
        "article": "a",
        "display": "statutory city",
        "preposition": "in",
    },
    "statutory town": {
        "article": "a",
        "display": "statutory town",
        "preposition": "in",
    },
    "strait": {
        "article": "a",
        "display": "strait",
        "preposition": "in",
    },
    "stream": {
        "article": "a",
        "display": "stream",
        "preposition": "in",
    },
    "sub-prefectural city": {
        "article": "a",
        "display": "sub-prefectural city",
        "preposition": "in",
    },
    "sub-prefecture-level city": {
        "article": "a",
        "display": "sub-prefectural city",
        "preposition": "in",
    },
    "subdistrict": {
        "article": "a",
        "display": "subdistrict",
        "preposition": "of",
    },
    "subdivision": {
        "article": "a",
        "display": "subdivision",
        "preposition": "of",
    },
    "submerged ghost town": {
        "article": "a",
        "display": "submerged ghost town",
        "preposition": "in",
    },
    "subprefecture": {
        "article": "a",
        "display": "subprefecture",
        "preposition": "of",
    },
    "subprovince": {
        "article": "a",
        "display": "subprovince",
        "preposition": "of",
    },
    "subprovincial city": {
        "article": "a",
        "display": "subprovincial city",
        "preposition": "in",
    },
    "sub-provincial city": {
        "article": "a",
        "display": "subprovincial city",
        "preposition": "in",
    },
    "subregion": {
        "article": "a",
        "display": "subregion",
        "preposition": "of",
    },
    "suburb": {
        "article": "a",
        "display": "suburb",
        "preposition": "of",
    },
    "suburban area": {
        "article": "a",
        "display": "suburban area",
        "preposition": "of",
    },
    "subway station": {
        "article": "a",
        "display": "subway station",
        "preposition": "in",
    },
    "supercontinent": {
        "article": "a",
        "display": "supercontinent",
        "preposition": "in",
    },
    "tehsil": {
        "article": "a",
        "display": "tehsil",
        "preposition": "in",
    },
    "territorial authority": {
        "article": "a",
        "display": "territorial authority",
        "preposition": "of",
    },
    "terrauth": {
        "article": "a",
        "display": "territorial authority",
        "preposition": "of",
    },
    "territory": {
        "article": "a",
        "display": "territory",
        "preposition": "of",
    },
    "terr": {
        "article": "a",
        "display": "territory",
        "preposition": "of",
    },
    "town": {
        "article": "a",
        "display": "town",
        "preposition": "in",
    },
    "town with bystatus": {
        "article": "a",
        "display": "town with bystatus",
        "preposition": "in",
    },
    "township": {
        "article": "a",
        "display": "township",
        "preposition": "in",
    },
    "twp": {
        "article": "a",
        "display": "township",
        "preposition": "in",
    },
    "township municipality": {
        "article": "a",
        "display": "township municipality",
        "preposition": "of",
    },
    "twpmun": {
        "article": "a",
        "display": "township municipality",
        "preposition": "of",
    },
    "traditional county": {
        "article": "a",
        "display": "traditional county",
        "preposition": "of",
    },
    "traditional region": {
        "article": "a",
        "display": "traditional region",
        "preposition": "in",
    },
    "treaty port": {
        "article": "a",
        "display": "treaty port",
        "preposition": "in",
    },
    "tribal jurisdictional area": {
        "article": "a",
        "display": "tribal jurisdictional area",
        "preposition": "in",
    },
    "tjarea": {
        "article": "a",
        "display": "tribal jurisdictional area",
        "preposition": "in",
    },
    "tributary": {
        "article": "a",
        "display": "tributary",
        "preposition": "of",
    },
    "underground station": {
        "article": "an",
        "display": "underground station",
        "preposition": "in",
    },
    "unincorporated area": {
        "article": "an",
        "display": "unincorporated area",
        "preposition": "of",
    },
    "unincorporated community": {
        "article": "an",
        "display": "unincorporated community",
        "preposition": "in",
    },
    "unincorporated territory": {
        "article": "an",
        "display": "unincorporated territory",
        "preposition": "of",
    },
    "union territory": {
        "article": "a",
        "display": "union territory",
        "preposition": "of",
    },
    "uterr": {
        "article": "a",
        "display": "union territory",
        "preposition": "of",
    },
    "unitary authority": {
        "article": "a",
        "display": "unitary authority",
        "preposition": "in",
    },
    "unitary district": {
        "article": "a",
        "display": "unitary district",
        "preposition": "in",
    },
    "united township municipality": {
        "article": "a",
        "display": "united township municipality",
        "preposition": "in",
    },
    "utwpmun": {
        "article": "a",
        "display": "united township municipality",
        "preposition": "in",
    },
    "unrecognised country": {
        "article": "an",
        "display": "unrecognised country",
        "preposition": "in",
    },
    "unrecognized country": {
        "article": "an",
        "display": "unrecognized country",
        "preposition": "in",
    },
    "urban area": {
        "article": "an",
        "display": "urban area",
        "preposition": "of",
    },
    "urban township": {
        "article": "an",
        "display": "urban township",
        "preposition": "in",
    },
    "urban-type settlement": {
        "article": "an",
        "display": "urban-type settlement",
        "preposition": "in",
    },
    "valley": {
        "article": "a",
        "display": "valley",
        "preposition": "in",
    },
    "val": {
        "article": "a",
        "display": "valley",
        "preposition": "in",
    },
    "village": {
        "article": "a",
        "display": "village",
        "preposition": "in",
    },
    "village municipality": {
        "article": "a",
        "display": "village municipality",
        "preposition": "of",
    },
    "voivodeship": {
        "article": "a",
        "display": "voivodeship",
        "preposition": "of",
    },
    "voi": {
        "article": "a",
        "display": "voivodeship",
        "preposition": "of",
    },
    "volcano": {
        "article": "a",
        "display": "volcano",
        "preposition": "in",
    },
    "ward": {
        "article": "a",
        "display": "ward",
        "preposition": "of",
    },
    "watercourse": {
        "article": "a",
        "display": "watercourse",
        "preposition": "in",
    },
    "zone": {
        "article": "a",
        "display": "zone",
        "preposition": "of",
    },
}
# 386 + 79 = 465

# Missing one...
placetypes["locale"] = {
    "article": "a",
    "display": "locale",
    "preposition": "of",
}


qualifiers = {
    "abandoned": "abandoned",
    "affluent": "affluent",
    "agricultural": "agricultural",
    "ancient": "ancient",
    "autonomous": "autonomous",
    "beachfront": "beachfront",
    "beachside": "beachfront",
    "business": "business",
    "cattle": "cattle",
    "chartered": "chartered",
    "coastal": "coastal",
    "commercial": "commercial",
    "declining": "declining",
    "deserted": "deserted",
    "east": "east",
    "eastern": "eastern",
    "extinct": "extinct",
    "farming": "farming",
    "fashionable": "fashionable",
    "fictional": "fictional",
    "fishing": "fishing",
    "former": "former",
    "high": "high",
    "hilly": "hilly",
    "historic": "historical",
    "historical": "historical",
    "holy": "holy",
    "huge": "huge",
    "important": "important",
    "incorporated": "incorporated",
    "industrial": "industrial",
    "inland": "inland",
    "inner": "inner",
    "large": "large",
    "left": "left",
    "logging": "logging",
    "long": "long",
    "low": "low",
    "major": "major",
    "maritime": "maritime",
    "mediaeval": "mediaeval",
    "medieval": "medieval",
    "mining": "mining",
    "minor": "minor",
    "modern": "modern",
    "mythological": "mythological",
    "north": "north",
    "northeast": "northeast",
    "northeastern": "northeastern",
    "northern": "northern",
    "northwest": "northwest",
    "northwestern": "northwestern",
    "outer": "outer",
    "outlying": "outlying",
    "overseas": "overseas",
    "planned": "planned",
    "railroad": "railroad",
    "railway": "railway",
    "religious": "religious",
    "remote": "remote",
    "residential": "residential",
    "right": "right",
    "riverside": "riverside",
    "rural": "rural",
    "sacred": "sacred",
    "seaside": "coastal",
    "secular": "secular",
    "short": "short",
    "sizable": "sizable",
    "small": "small",
    "south": "south",
    "southeast": "southeast",
    "southeastern": "southeastern",
    "southern": "southern",
    "southwest": "southwest",
    "southwestern": "southwestern",
    "special": "special",
    "suburban": "suburban",
    "tiny": "tiny",
    "traditional": "traditional",
    "unincorporated": "unincorporated",
    "urban": "urban",
    "wealthy": "wealthy",
    "west": "west",
    "western": "western",
}
# 85
