"""
List of mediawiki namespaces per language.
Auto-generated with `python -m scripts`.
"""

# START
namespaces = {
    "ca": [
        "Ajuda",
        "Ajuda Discussió",
        "Categoria",
        "Categoria Discussió",
        "Discussió",
        "Especial",
        "Fitxer",
        "Fitxer Discussió",
        "Gadget",
        "Gadget definition",
        "Gadget definition talk",
        "Gadget talk",
        "Media",
        "MediaWiki",
        "MediaWiki Discussió",
        "Mòdul",
        "Mòdul Discussió",
        "Plantilla",
        "Plantilla Discussió",
        "TimedText",
        "TimedText talk",
        "Usuari",
        "Usuari Discussió",
        "Viccionari",
        "Viccionari Discussió",
    ],
    "de": [
        "Benutzer",
        "Benutzer Diskussion",
        "Datei",
        "Datei Diskussion",
        "Diskussion",
        "Flexion",
        "Flexion Diskussion",
        "Gadget",
        "Gadget Diskussion",
        "Gadget-Definition",
        "Gadget-Definition Diskussion",
        "Hilfe",
        "Hilfe Diskussion",
        "Kategorie",
        "Kategorie Diskussion",
        "MediaWiki",
        "MediaWiki Diskussion",
        "Medium",
        "Modul",
        "Modul Diskussion",
        "Reim",
        "Reim Diskussion",
        "Rekonstruktion",
        "Rekonstruktion Diskussion",
        "Spezial",
        "Thesaurus",
        "Thesaurus Diskussion",
        "TimedText",
        "TimedText talk",
        "Verzeichnis",
        "Verzeichnis Diskussion",
        "Vorlage",
        "Vorlage Diskussion",
        "Wiktionary",
        "Wiktionary Diskussion",
    ],
    "el": [
        "Gadget",
        "Gadget definition",
        "Gadget definition talk",
        "Gadget talk",
        "MediaWiki",
        "Module",
        "Module talk",
        "TimedText",
        "TimedText talk",
        "Αρχείο",
        "Βικιλεξικό",
        "Βοήθεια",
        "Ειδικό",
        "Κατηγορία",
        "Μέσο",
        "Παράρτημα",
        "Πρότυπο",
        "Συζήτηση",
        "Συζήτηση MediaWiki",
        "Συζήτηση αρχείου",
        "Συζήτηση βικιλεξικού",
        "Συζήτηση βοήθειας",
        "Συζήτηση κατηγορίας",
        "Συζήτηση παραρτήματος",
        "Συζήτηση προτύπου",
        "Συζήτηση χρήστη",
        "Χρήστης",
    ],
    "en": [
        "Appendix",
        "Appendix talk",
        "Category",
        "Category talk",
        "Citations",
        "Citations talk",
        "Concordance",
        "Concordance talk",
        "File",
        "File talk",
        "Gadget",
        "Gadget definition",
        "Gadget definition talk",
        "Gadget talk",
        "Help",
        "Help talk",
        "Index",
        "Index talk",
        "Media",
        "MediaWiki",
        "MediaWiki talk",
        "Module",
        "Module talk",
        "Reconstruction",
        "Reconstruction talk",
        "Rhymes",
        "Rhymes talk",
        "Sign gloss",
        "Sign gloss talk",
        "Special",
        "Summary",
        "Summary talk",
        "Talk",
        "Template",
        "Template talk",
        "Thesaurus",
        "Thesaurus talk",
        "Thread",
        "Thread talk",
        "TimedText",
        "TimedText talk",
        "Transwiki",
        "Transwiki talk",
        "User",
        "User talk",
        "Wiktionary",
        "Wiktionary talk",
    ],
    "es": [
        "Accesorio",
        "Accesorio definición",
        "Accesorio definición discusión",
        "Accesorio discusión",
        "Apéndice",
        "Apéndice Discusión",
        "Archivo",
        "Archivo discusión",
        "Ayuda",
        "Ayuda discusión",
        "Categoría",
        "Categoría discusión",
        "Discusión",
        "Especial",
        "MediaWiki",
        "MediaWiki discusión",
        "Medio",
        "Módulo",
        "Módulo discusión",
        "Plantilla",
        "Plantilla discusión",
        "TimedText",
        "TimedText talk",
        "Usuario",
        "Usuario discusión",
        "Wikcionario",
        "Wikcionario discusión",
    ],
    "fr": [
        "Aide",
        "Annexe",
        "Catégorie",
        "Conjugaison",
        "Discussion",
        "Discussion Annexe",
        "Discussion Conjugaison",
        "Discussion MediaWiki",
        "Discussion Portail",
        "Discussion Projet",
        "Discussion Racine",
        "Discussion Reconstruction",
        "Discussion Rime",
        "Discussion Thésaurus",
        "Discussion Transwiki",
        "Discussion Tutoriel",
        "Discussion Wiktionnaire",
        "Discussion aide",
        "Discussion catégorie",
        "Discussion définition de gadget",
        "Discussion fichier",
        "Discussion gadget",
        "Discussion module",
        "Discussion modèle",
        "Discussion utilisateur",
        "Définition de gadget",
        "Fichier",
        "Gadget",
        "MediaWiki",
        "Module",
        "Modèle",
        "Média",
        "Portail",
        "Projet",
        "Racine",
        "Reconstruction",
        "Rime",
        "Spécial",
        "Sujet",
        "Thésaurus",
        "TimedText",
        "TimedText talk",
        "Translations",
        "Translations talk",
        "Transwiki",
        "Tutoriel",
        "Utilisateur",
        "Wiktionnaire",
    ],
    "it": [
        "Accessorio",
        "Aiuto",
        "Appendice",
        "Categoria",
        "Definizione accessorio",
        "Discussione",
        "Discussioni MediaWiki",
        "Discussioni Wikizionario",
        "Discussioni accessorio",
        "Discussioni aiuto",
        "Discussioni appendice",
        "Discussioni categoria",
        "Discussioni definizione accessorio",
        "Discussioni file",
        "Discussioni modulo",
        "Discussioni template",
        "Discussioni utente",
        "File",
        "Media",
        "MediaWiki",
        "Modulo",
        "Speciale",
        "Template",
        "TimedText",
        "TimedText talk",
        "Utente",
        "Wikizionario",
    ],
    "no": [
        "Bruker",
        "Brukerdiskusjon",
        "Diskusjon",
        "Fil",
        "Fildiskusjon",
        "Gadget",
        "Gadget definition",
        "Gadget definition talk",
        "Gadget talk",
        "Hjelp",
        "Hjelpdiskusjon",
        "Kategori",
        "Kategoridiskusjon",
        "Mal",
        "Maldiskusjon",
        "MediaWiki",
        "MediaWiki-diskusjon",
        "Medium",
        "Modul",
        "Moduldiskusjon",
        "Spesial",
        "Tillegg",
        "Tilleggdiskusjon",
        "TimedText",
        "TimedText talk",
        "Wiktionary",
        "Wiktionary-diskusjon",
    ],
    "pt": [
        "Ajuda",
        "Ajuda Discussão",
        "Apêndice",
        "Apêndice Discussão",
        "Categoria",
        "Categoria Discussão",
        "Citações",
        "Citações Discussão",
        "Discussão",
        "Especial",
        "Ficheiro",
        "Ficheiro Discussão",
        "Gadget",
        "Gadget definition",
        "Gadget definition talk",
        "Gadget talk",
        "MediaWiki",
        "MediaWiki Discussão",
        "Multimédia",
        "Módulo",
        "Módulo Discussão",
        "Portal",
        "Portal Discussão",
        "Predefinição",
        "Predefinição Discussão",
        "Rimas",
        "Rimas Discussão",
        "TimedText",
        "TimedText talk",
        "Utilizador",
        "Utilizador Discussão",
        "Vocabulário",
        "Vocabulário Discussão",
        "Wikcionário",
        "Wikcionário Discussão",
    ],
    "ru": [
        "MediaWiki",
        "TimedText",
        "TimedText talk",
        "Викисловарь",
        "Гаджет",
        "Индекс",
        "Категория",
        "Конкорданс",
        "Медиа",
        "Модуль",
        "Обсуждение",
        "Обсуждение MediaWiki",
        "Обсуждение Викисловаря",
        "Обсуждение гаджета",
        "Обсуждение индекса",
        "Обсуждение категории",
        "Обсуждение конкорданса",
        "Обсуждение модуля",
        "Обсуждение определения гаджета",
        "Обсуждение приложения",
        "Обсуждение рифм",
        "Обсуждение справки",
        "Обсуждение участника",
        "Обсуждение файла",
        "Обсуждение шаблона",
        "Определение гаджета",
        "Приложение",
        "Рифмы",
        "Служебная",
        "Справка",
        "Участник",
        "Файл",
        "Шаблон",
    ],
    "sv": [
        "Användardiskussion",
        "Användare",
        "Appendix",
        "Appendixdiskussion",
        "Diskussion",
        "Fil",
        "Fildiskussion",
        "Gadget",
        "Gadget definition",
        "Gadget definition talk",
        "Gadget talk",
        "Hjälp",
        "Hjälpdiskussion",
        "Kategori",
        "Kategoridiskussion",
        "Mall",
        "Malldiskussion",
        "Media",
        "MediaWiki",
        "MediaWiki-diskussion",
        "Modul",
        "Moduldiskussion",
        "Rimord",
        "Rimordsdiskussion",
        "Special",
        "TimedText",
        "TimedText talk",
        "Transwiki",
        "Transwikidiskussion",
        "Wiktionary",
        "Wiktionarydiskussion",
    ],
}
# END
