"""
List of mediawiki namespaces per language.
Auto-generated with `python -m scripts`.
"""

# START
namespaces = {
    "ca": [
        "Media",
        "Especial",
        "Discussió",
        "Usuari",
        "Usuari Discussió",
        "Viccionari",
        "Viccionari Discussió",
        "Fitxer",
        "Fitxer Discussió",
        "MediaWiki",
        "MediaWiki Discussió",
        "Plantilla",
        "Plantilla Discussió",
        "Ajuda",
        "Ajuda Discussió",
        "Categoria",
        "Categoria Discussió",
        "TimedText",
        "TimedText talk",
        "Mòdul",
        "Mòdul Discussió",
        "Gadget",
        "Gadget talk",
        "Gadget definition",
        "Gadget definition talk",
    ],
    "de": [
        "Medium",
        "Spezial",
        "Diskussion",
        "Benutzer",
        "Benutzer Diskussion",
        "Wiktionary",
        "Wiktionary Diskussion",
        "Datei",
        "Datei Diskussion",
        "MediaWiki",
        "MediaWiki Diskussion",
        "Vorlage",
        "Vorlage Diskussion",
        "Hilfe",
        "Hilfe Diskussion",
        "Kategorie",
        "Kategorie Diskussion",
        "Verzeichnis",
        "Verzeichnis Diskussion",
        "Thesaurus",
        "Thesaurus Diskussion",
        "Reim",
        "Reim Diskussion",
        "Flexion",
        "Flexion Diskussion",
        "Rekonstruktion",
        "Rekonstruktion Diskussion",
        "TimedText",
        "TimedText talk",
        "Modul",
        "Modul Diskussion",
        "Gadget",
        "Gadget Diskussion",
        "Gadget-Definition",
        "Gadget-Definition Diskussion",
    ],
    "el": [
        "Μέσο",
        "Ειδικό",
        "Συζήτηση",
        "Χρήστης",
        "Συζήτηση χρήστη",
        "Βικιλεξικό",
        "Συζήτηση βικιλεξικού",
        "Αρχείο",
        "Συζήτηση αρχείου",
        "MediaWiki",
        "Συζήτηση MediaWiki",
        "Πρότυπο",
        "Συζήτηση προτύπου",
        "Βοήθεια",
        "Συζήτηση βοήθειας",
        "Κατηγορία",
        "Συζήτηση κατηγορίας",
        "Παράρτημα",
        "Συζήτηση παραρτήματος",
        "TimedText",
        "TimedText talk",
        "Module",
        "Module talk",
        "Gadget",
        "Gadget talk",
        "Gadget definition",
        "Gadget definition talk",
    ],
    "en": [
        "Media",
        "Special",
        "Talk",
        "User",
        "User talk",
        "Wiktionary",
        "Wiktionary talk",
        "File",
        "File talk",
        "MediaWiki",
        "MediaWiki talk",
        "Template",
        "Template talk",
        "Help",
        "Help talk",
        "Category",
        "Category talk",
        "Thread",
        "Thread talk",
        "Summary",
        "Summary talk",
        "Appendix",
        "Appendix talk",
        "Concordance",
        "Concordance talk",
        "Index",
        "Index talk",
        "Rhymes",
        "Rhymes talk",
        "Transwiki",
        "Transwiki talk",
        "Thesaurus",
        "Thesaurus talk",
        "Citations",
        "Citations talk",
        "Sign gloss",
        "Sign gloss talk",
        "Reconstruction",
        "Reconstruction talk",
        "TimedText",
        "TimedText talk",
        "Module",
        "Module talk",
        "Gadget",
        "Gadget talk",
        "Gadget definition",
        "Gadget definition talk",
    ],
    "es": [
        "Medio",
        "Especial",
        "Discusión",
        "Usuario",
        "Usuario discusión",
        "Wikcionario",
        "Wikcionario discusión",
        "Archivo",
        "Archivo discusión",
        "MediaWiki",
        "MediaWiki discusión",
        "Plantilla",
        "Plantilla discusión",
        "Ayuda",
        "Ayuda discusión",
        "Categoría",
        "Categoría discusión",
        "Apéndice",
        "Apéndice Discusión",
        "TimedText",
        "TimedText talk",
        "Módulo",
        "Módulo discusión",
        "Accesorio",
        "Accesorio discusión",
        "Accesorio definición",
        "Accesorio definición discusión",
    ],
    "fr": [
        "Média",
        "Spécial",
        "Discussion",
        "Utilisateur",
        "Discussion utilisateur",
        "Wiktionnaire",
        "Discussion Wiktionnaire",
        "Fichier",
        "Discussion fichier",
        "MediaWiki",
        "Discussion MediaWiki",
        "Modèle",
        "Discussion modèle",
        "Aide",
        "Discussion aide",
        "Catégorie",
        "Discussion catégorie",
        "Annexe",
        "Discussion Annexe",
        "Transwiki",
        "Discussion Transwiki",
        "Portail",
        "Discussion Portail",
        "Thésaurus",
        "Discussion Thésaurus",
        "Projet",
        "Discussion Projet",
        "Reconstruction",
        "Discussion Reconstruction",
        "Tutoriel",
        "Discussion Tutoriel",
        "Rime",
        "Discussion Rime",
        "Conjugaison",
        "Discussion Conjugaison",
        "Racine",
        "Discussion Racine",
        "TimedText",
        "TimedText talk",
        "Module",
        "Discussion module",
        "Translations",
        "Translations talk",
        "Gadget",
        "Discussion gadget",
        "Définition de gadget",
        "Discussion définition de gadget",
        "Sujet",
    ],
    "it": [
        "Media",
        "Speciale",
        "Discussione",
        "Utente",
        "Discussioni utente",
        "Wikizionario",
        "Discussioni Wikizionario",
        "File",
        "Discussioni file",
        "MediaWiki",
        "Discussioni MediaWiki",
        "Template",
        "Discussioni template",
        "Aiuto",
        "Discussioni aiuto",
        "Categoria",
        "Discussioni categoria",
        "Appendice",
        "Discussioni appendice",
        "TimedText",
        "TimedText talk",
        "Modulo",
        "Discussioni modulo",
        "Accessorio",
        "Discussioni accessorio",
        "Definizione accessorio",
        "Discussioni definizione accessorio",
    ],
    "no": [
        "Medium",
        "Spesial",
        "Diskusjon",
        "Bruker",
        "Brukerdiskusjon",
        "Wiktionary",
        "Wiktionary-diskusjon",
        "Fil",
        "Fildiskusjon",
        "MediaWiki",
        "MediaWiki-diskusjon",
        "Mal",
        "Maldiskusjon",
        "Hjelp",
        "Hjelpdiskusjon",
        "Kategori",
        "Kategoridiskusjon",
        "Tillegg",
        "Tilleggdiskusjon",
        "TimedText",
        "TimedText talk",
        "Modul",
        "Moduldiskusjon",
        "Gadget",
        "Gadget talk",
        "Gadget definition",
        "Gadget definition talk",
    ],
    "pt": [
        "Multimédia",
        "Especial",
        "Discussão",
        "Utilizador",
        "Utilizador Discussão",
        "Wikcionário",
        "Wikcionário Discussão",
        "Ficheiro",
        "Ficheiro Discussão",
        "MediaWiki",
        "MediaWiki Discussão",
        "Predefinição",
        "Predefinição Discussão",
        "Ajuda",
        "Ajuda Discussão",
        "Categoria",
        "Categoria Discussão",
        "Apêndice",
        "Apêndice Discussão",
        "Vocabulário",
        "Vocabulário Discussão",
        "Rimas",
        "Rimas Discussão",
        "Portal",
        "Portal Discussão",
        "Citações",
        "Citações Discussão",
        "TimedText",
        "TimedText talk",
        "Módulo",
        "Módulo Discussão",
        "Gadget",
        "Gadget talk",
        "Gadget definition",
        "Gadget definition talk",
    ],
    "ru": [
        "Медиа",
        "Служебная",
        "Обсуждение",
        "Участник",
        "Обсуждение участника",
        "Викисловарь",
        "Обсуждение Викисловаря",
        "Файл",
        "Обсуждение файла",
        "MediaWiki",
        "Обсуждение MediaWiki",
        "Шаблон",
        "Обсуждение шаблона",
        "Справка",
        "Обсуждение справки",
        "Категория",
        "Обсуждение категории",
        "Приложение",
        "Обсуждение приложения",
        "Конкорданс",
        "Обсуждение конкорданса",
        "Индекс",
        "Обсуждение индекса",
        "Рифмы",
        "Обсуждение рифм",
        "TimedText",
        "TimedText talk",
        "Модуль",
        "Обсуждение модуля",
        "Гаджет",
        "Обсуждение гаджета",
        "Определение гаджета",
        "Обсуждение определения гаджета",
    ],
    "sv": [
        "Media",
        "Special",
        "Diskussion",
        "Användare",
        "Användardiskussion",
        "Wiktionary",
        "Wiktionarydiskussion",
        "Fil",
        "Fildiskussion",
        "MediaWiki",
        "MediaWiki-diskussion",
        "Mall",
        "Malldiskussion",
        "Hjälp",
        "Hjälpdiskussion",
        "Kategori",
        "Kategoridiskussion",
        "Appendix",
        "Appendixdiskussion",
        "Rimord",
        "Rimordsdiskussion",
        "Transwiki",
        "Transwikidiskussion",
        "TimedText",
        "TimedText talk",
        "Modul",
        "Moduldiskussion",
        "Gadget",
        "Gadget talk",
        "Gadget definition",
        "Gadget definition talk",
    ],
}
# END
